name: Run plan and apply

on:
  push:
    branches: ['main']

jobs:
  terraform-plan:
    name: terraform plan
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:1.7.5
    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_CLOUD_TOKEN }}
      TF_VAR_provider_token: ${{ secrets.TF_CLOUD_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: terraform init
        run: terraform init

      - name: terraform plan
        run: terraform plan -out tfplan

      - uses: actions/upload-artifact@v4
        with:
          name: tfplan-${{ github.sha }}
          path: tfplan
          retention-days: 7

  terraform-apply:
    name: terraform apply
    runs-on: ubuntu-latest
    environment: terraform-cicd-2-env
    needs: [ 'terraform-plan' ]
    container:
      image: hashicorp/terraform:1.7.5
    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_CLOUD_TOKEN }}
      TF_VAR_provider_token: ${{ secrets.TF_CLOUD_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: tfplan-${{ github.sha }}

      - name: terraform init
        run: terraform init

      - name: terraform apply
        run: terraform apply -auto-approve tfplan

  update-infracost-base:
    name: Update infracost base
    permissions:
      contents: write
    runs-on: ubuntu-latest
    container:
      image: infracost/infracost:ci-0.10.35
    env:
      INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
    steps:
      - uses: actions/checkout@v4

      - name: Update infracost base
        run: infracost breakdown --path . --format json --out-file infracost-base.json

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Update infracost base [skip ci]'
          skip_fetch: true
          skip_checkout: true
