name: Run checks and plan

on:
  pull_request:
    branches: ['main']

jobs:
  terraform-fmt:
    name: terraform fmt
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:1.7.5
    steps:
      - uses: actions/checkout@v4

      - name: terraform fmt
        run: terraform fmt -recursive -check -diff

  terraform-validate:
    name: terraform validate
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:1.7.5
    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_CLOUD_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: terraform init
        run: terraform init

      - name: terraform validate
        run: terraform validate

  tflint:
    name: tflint checks
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/terraform-linters/tflint:v0.50.3
    steps:
      - uses: actions/checkout@v4

      - name: tflint
        run: tflint --recursive

  trivy:
    name: trivy security checks
    runs-on: ubuntu-latest
    container:
      image: aquasec/trivy:0.52.2
    steps:
      - uses: actions/checkout@v4

      - name: trivy
        run: trivy config ./

  terraform-plan:
    name: terraform plan
    runs-on: ubuntu-latest
    needs: [ 'terraform-validate', 'terraform-fmt', 'tflint', 'trivy' ]
    container:
      image: hashicorp/terraform:1.7.5
    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_CLOUD_TOKEN }}
      TF_VAR_provider_token: ${{ secrets.TF_CLOUD_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: terraform init
        run: terraform init

      - name: terraform plan
        run: terraform plan -lock=false

  infracost:
    name: Infracost diff
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    env:
      INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
    steps:
      - name: Setup Infracost
        uses: infracost/actions/setup@v3
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          ref: '${{ github.event.pull_request.base.ref }}'

      - name: Generate Infracost cost estimate baseline
        run: |
          infracost breakdown --path=. \
                              --format=json \
                              --out-file=/tmp/infracost-base.json

      - name: Checkout PR branch
        uses: actions/checkout@v4

      - name: Generate Infracost diff
        run: |
          infracost diff --path=. \
                         --format=json \
                         --compare-to=/tmp/infracost-base.json \
                         --out-file=/tmp/infracost.json
      
      - name: Post Infracost comment
        run: |
          infracost comment github --path=/tmp/infracost.json \
                                   --repo=$GITHUB_REPOSITORY \
                                   --github-token=${{ github.token }} \
                                   --pull-request=${{ github.event.pull_request.number }} \
                                   --behavior=update
