name: Renovate
on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    container:
      image: renovate/renovate:37.279-slim
    steps:
      - name: Self-hosted Renovate
        env:
          PAT_FOR_RENOVATE: ${{ secrets.PAT_FOR_RENOVATE }}
        run: renovate --token ${PAT_FOR_RENOVATE} --platform=github elevate-ops/terraform-cicd-2
